services:
  backend:
    # build:
    #   context: ./backend
    image: backend
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
    networks:
      - appnet

  frontend:
    # build:
    #   context: ./frontend
    image: frontend
    container_name: frontend
    ports:
      - "8501:8501"
    environment:
      - API_BASE=http://backend:8000/api
    depends_on:
      - backend
    restart: always
    networks:
      - appnet

networks:
  appnet:
